apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oxauth
  labels:
    app: oxauth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oxauth
    spec:
      hostAliases:
      - ip: 10.24.128.91
        hostnames:
        - dev.kube.org
      containers:
        - name: oxauth
          image: gluufederation/oxauth:latest
          env:
            - name: GLUU_KV_HOST
              value: "consul"
            - name: GLUU_LDAP_URL
              value: "opendj:1636"
          ports:
          - containerPort: 8080
            name: jetty-oxauth
          - containerPort: 443
            name: jetty-https