apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: opendj
spec:
  serviceName: opendj
  replicas: 1
  template:
    metadata:
      labels:
        app: opendj
    spec:
      containers:
        - name: opendj
          image: 'gluufederation/opendj:latest'
          env:
            - name: GLUU_KV_HOST
              value: "consul"
            - name: GLUU_LDAP_INIT
              value: "true"
            - name: GLUU_LDAP_INIT_HOST
              value: "opendj"
            - name: GLUU_LDAP_INIT_PORT
              value: "1636"
            - name: GLUU_LDAP_ADDR_INTERFACE
              value: "eth0"
            - name: GLUU_OXTRUST_CONFIG_GENERATION
              value: "true"
          ports:
            - containerPort: 1636
              name: ldaps
            - containerPort: 1389
              name: ldap
            - containerPort: 8989
              name: replication
            - containerPort: 4444
              name: admin