apiVersion: v1
kind: Service
metadata:
  name: oxtrust
  labels:
    name: oxtrust
spec:
  ports:
  - port: 8080
    name: jetty-oxtrust
    targetPort: 8080
  - port: 443
    name: jetty-https
    targetPort: 443
  selector:
    app: oxtrust
  sessionAffinity: ClientIP
  type: NodePort